### ISSUE TITLE
出现System Error

### ISSUE THREAD

**Issue by Bingxiusmall** [hydro-dev/Hydro#466] opened 2022-11-30 14:20 UTC
自己新建了一道题，提交SE
https://hydro.ac/d/GXOJ/record/63874f662d0d63504376deca

**Comment by HayatoOvO** [comment] 2022-11-30 14:27
Maybe your topic file is **too large.** And your memory usage is too large. Maybe you should open your evaluation stack a little wider.

In addition, this problem should be raised in “hello, HydroOJ” or “HydroOJ user groups”.

**Comment by undefined-moe** [comment] 2022-11-30 14:35
I'm unable to reproduce this issue. closing now.
Feel free to re-open it if you are sure if there's a problem.

**Closed as completed by undefined-moe** 2022-11-30 14:35 UTC

**Comment by Bingxiusmall** [comment] 2022-12-01 12:18
How to edit evaluation stack?Probably it's because that.

**Comment by HayatoOvO** [comment] 2022-12-01 12:31
> How to edit evaluation stack?Probably it's because that.

Please go to the "setting_limits" column on the "manage/setting" page to search for it in your webpage version of OnlineJudge.

**Comment by Bingxiusmall** [comment] 2022-12-01 22:45
Where?Can you give me an example?(like www.???.???/??????)

**Comment by Bingxiusmall** [comment] 2022-12-03 08:13
Where?Can you give me an example?(like www.???.???/??????)
